
cache: "./data/cache"
datasets:
  - name: "2017"
    file: "$FILE_2017"
    palette:
    - 0xFFFFFFFF
    - 0xE4E4E4FF
    - 0x888888FF
    - 0x222222FF
    - 0xFFA7D1FF
    - 0xE50000FF
    - 0xE59500FF
    - 0xA06A42FF
    - 0xE5D900FF
    - 0x94E044FF
    - 0x02BE01FF
    - 0x00E5F0FF
    - 0x0083C7FF
    - 0x0000EAFF
    - 0xE04AFFFF
    - 0x820080FF
    sizeX: 1000
    sizeY: 1000
    tileSize: 500
    interval: 500000
  - name: "2022"
    file: "$FILE_2022"
    palette:
      - 0xFFFFFFFF
      - 0xFFF8B8FF
      - 0xFFD635FF
      - 0xFFB470FF
      - 0xFFA800FF
      - 0xFF99AAFF
      - 0xFF4500FF
      - 0xFF3881FF
      - 0xE4ABFFFF
      - 0xDE107FFF
      - 0xD4D7D9FF
      - 0xBE0039FF
      - 0xB44AC0FF
      - 0x9C6926FF
      - 0x94B3FFFF
      - 0x898D90FF
      - 0x811E9FFF
      - 0x7EED56FF
      - 0x6D482FFF
      - 0x6D001AFF
      - 0x6A5CFFFF
      - 0x51E9F4FF
      - 0x515252FF
      - 0x493AC1FF
      - 0x3690EAFF
      - 0x2450A4FF
      - 0x00CCC0FF
      - 0x00CC78FF
      - 0x00A368FF
      - 0x009EAAFF
      - 0x00756FFF
      - 0x000000FF
    sizeX: 2000
    sizeY: 2000
    tileSize: 500
    interval: 500000
