
datasets:
  - name: "2017"
    tiles:
      - data/cache/2017_log_*.bin
    palette:
      - 0xFFFFFF
      - 0xE4E4E4
      - 0x888888
      - 0x222222
      - 0xFFA7D1
      - 0xE50000
      - 0xE59500
      - 0xA06A42
      - 0xE5D900
      - 0x94E044
      - 0x02BE01
      - 0x00E5F0
      - 0x0083C7
      - 0x0000EA
      - 0xE04AFF
      - 0x820080
    size_x: 1000
    size_y: 1000
    size_tile: 500
    interval: 500000
  - name: "2022"
    tiles:
      - data/cache/2022_log_*.bin
    palette:
      - 0xFFFFFF
      - 0xFFF8B8
      - 0xFFD635
      - 0xFFB470
      - 0xFFA800
      - 0xFF99AA
      - 0xFF4500
      - 0xFF3881
      - 0xE4ABFF
      - 0xDE107F
      - 0xD4D7D9
      - 0xBE0039
      - 0xB44AC0
      - 0x9C6926
      - 0x94B3FF
      - 0x898D90
      - 0x811E9F
      - 0x7EED56
      - 0x6D482F
      - 0x6D001A
      - 0x6A5CFF
      - 0x51E9F4
      - 0x515252
      - 0x493AC1
      - 0x3690EA
      - 0x2450A4
      - 0x00CCC0
      - 0x00CC78
      - 0x00A368
      - 0x009EAA
      - 0x00756F
      - 0x000000
    size_x: 2000
    size_y: 2000
    size_tile: 500
    interval: 500000
